use_frameworks!

target 'BalloonUI_Example' do

  pod 'Reusable'
  pod 'Cartography'
  pod 'BalloonUI', :path => '../'
  pod 'ViewSizeCalculator'
  pod 'Then'
  pod 'SwiftyJSON'
  pod 'TextAttributesUtil'
  pod 'Measure'
  pod 'Reveal-iOS-SDK'

  target 'BalloonUI_Tests' do
    inherit! :search_paths

    
  end
end
